name: Automatic build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: goto-bus-stop/setup-zig@v2

    - name: Build test
      run: |
        zig build -Dtarget=x86_64-linux-gnu
        zig build -Dtarget=x86_64-linux-musl

        zig build -Dtarget=aarch64-linux-gnu
        zig build -Dtarget=aarch64-linux-musl

        zig build -Dtarget=x86-linux-gnu
        zig build -Dtarget=x86-linux-musl

        zig build -Dtarget=arm-linux-gnueabi
        zig build -Dtarget=arm-linux-musleabi

        # TODO
        #    - name: Test
        #      run: |
        #        zig build test
        #        zig build test -Doptimize=ReleaseSafe
        #        zig build test -Doptimize=ReleaseFast
        #        zig build test -Doptimize=ReleaseSmall

    - name: Upload build
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "continuous"
        prerelease: true
        title: "Continuous Build"
          #        files: |
